openapi: "3.1.0"
info:
  version: 1.0.0
  title: Conference Sessions API
  description: API to fetch conference sessions with optional filters
servers:
  - url: https://siop-schedule-gpt.vercel.app
paths:
  /sessions:
    get:
      summary: Fetch all sessions with optional filters
      operationId: getSessions
      tags:
        - sessions
      parameters:
        - name: event_name
          in: query
          description: Filter by event name
          required: false
          schema:
            type: string
        - name: date
          in: query
          description: Filter by date (YYYY-MM-DD format)
          required: true
          schema:
            type: string
            format: date
        - name: track_id
          in: query
          description: Filter by track ID
          required: false
          schema:
            type: integer
        - name: speaker_id
          in: query
          description: Filter by speaker ID
          required: false
          schema:
            type: integer
        - name: search
          in: query
          description: Search text in session name and description
          required: true
          schema:
            type: string
      responses:
        "200":
          description: A list of filtered sessions
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Session"
        "400":
          description: Invalid query parameters
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "500":
          description: Server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    Session:
      type: object
      required:
        - id
        - name
        - start_time
        - end_time
        - date
      properties:
        id:
          type: integer
        name:
          type: string
        start_time:
          type: string
          format: time
        end_time:
          type: string
          format: time
        date:
          type: string
          format: date
        location:
          type: string
          nullable: true
        description:
          type: string
          nullable: true
        session_id:
          type: string
          nullable: true
        is_virtual:
          type: boolean
          default: false
        event_name:
          type: string
          nullable: true
        timezone:
          type: string
          nullable: true
        session_type:
          type: string
          nullable: true
        tracks:
          type: array
          items:
            $ref: "#/components/schemas/Track"
        speakers:
          type: array
          items:
            $ref: "#/components/schemas/Speaker"
        subSessions:
          type: array
          items:
            $ref: "#/components/schemas/SubSession"
    Track:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
        name:
          type: string
    Speaker:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
        name:
          type: string
    SubSession:
      type: object
      required:
        - id
        - parent_session_id
        - name
      properties:
        id:
          type: integer
        parent_session_id:
          type: integer
        name:
          type: string
        description:
          type: string
          nullable: true
        speakers:
          type: array
          items:
            $ref: "#/components/schemas/Speaker"
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
        message:
          type: string
